import type { ActionOption, GameSession } from './types';

type Translate = (key: string, params?: Record<string, string | number>) => string;

/**
 * The label to show on a choice button.
 *
 * Most options are the author's own words and are shown as written. A handful
 * are generated by the engine — bidding in an auction, accepting a trade — and
 * those arrive in English because the server has no idea which language the
 * player is reading in. Recognising them by their stable IDs is what lets a
 * Russian player see "Пас" instead of "Pass" without the engine growing a
 * translation layer of its own.
 */
export function optionLabel(
  option: ActionOption,
  t: Translate,
  context: { resource?: string } = {},
): string {
  switch (option.id) {
    case 'pass':
      return t('option.pass');
    case 'accept':
      return t('option.accept');
    case 'decline':
      return t('option.decline');
  }
  const bid = /^bid_(\d+)$/.exec(option.id);
  if (bid) {
    return t('option.bid', { amount: bid[1], resource: context.resource ?? '' }).trim();
  }
  return option.title;
}

/**
 * The heading above a pending choice.
 *
 * An auction is rebuilt from the session state rather than shown as the
 * server's sentence, because it changes with every bid and every player is
 * reading it in their own language. Anything else is the author's own title,
 * which no translation of ours could improve.
 */
export function pendingHeading(session: GameSession, t: Translate, fallbackKey: string): string {
  const pending = session.state.pendingAction;
  const auction = session.state.pendingAuction;
  if (pending?.type === 'auction_bid' && auction) {
    const leader = session.state.players.find((player) => player.id === auction.highBidderId);
    const standing = leader
      ? t('auction.leader', { name: leader.name, amount: `${auction.highBid} ${auction.resource}` })
      : t('auction.noBids');
    return `${t('auction.heading')} — ${standing}`;
  }
  return pending?.title || t(fallbackKey);
}
